# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time.
# Run every test

name: CI PipeLine

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('blog/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: |
        cd blog
        mvn clean install -DskipTests

    - name: Run Tests
      run: |
        cd blog
        mvn test
